Add states into Tasks
der-HANS/TaskManager pull request #7
Opened 2021-12-04 20:12 UTC by der-HANS

2021-12-06 08:27 UTC, greybutton requested changes

2021-12-06 08:27 UTC, greybutton commented on .rubocop.yml
> +  Enabled: false
почему убрал это правило?

2021-12-06 08:27 UTC, greybutton commented on test/models/task_test.rb
> +      eval("task.#{event}")
eval не надо использовать, у стейт машины есть функция fire_state_event

2021-12-07 09:51 UTC, der-HANS commented on .rubocop.yml
> +  Enabled: false
Данное правило кроме полезного функционала, дополнительно заменяет => на : в случае если ключ и значение являются символами, что сильно снижает читабельность, как пример

было 
transition :parked => :idling
или
:into_development => :in_development, :into_qa => :in_qa, :into_code_review => :in_code_review,

стало
transition parked: :idling
или
into_development: :in_development, into_qa: :in_qa, into_code_review: :in_code_review,

Если у вас ну прям очень жесткая политика в отношении стилей, которой должны использовать обучающиеся, просто укажите Заменить и можете закрывать пуллреквест, и я со своей стороны все поправлю.

2021-12-07 09:51 UTC, der-HANS commented on test/models/task_test.rb
> +      eval("task.#{event}")
Заменил: commit "Replace eval => fire_state_event"

2021-12-08 16:23 UTC, greybutton requested changes
в обучении была ссылка на конфиг рубокопа, наша политика в нем, менять этот файл без объективных причин не стоит

2021-12-08 18:02 UTC, der-HANS commented on .rubocop.yml
> +  Enabled: false
Поправил. (commit "Recover buggy _Use the new Ruby 1.9 hash syntax_ rubocop rule")

2021-12-08 19:28 UTC, der-HANS commented
Поправил. (commit "Recover buggy Use the new Ruby 1.9 hash syntax rubocop rule")

2021-12-08 19:56 UTC, greybutton requested changes

2021-12-08 19:56 UTC, greybutton commented on app/models/task.rb
> +    end
давай назовем события так, чтобы в них содержались действия т.е. через глаголы

2021-12-09 04:28 UTC, der-HANS commented on app/models/task.rb
> +    end
_into_состояние мне кажется наиболее коротким и вполне уместным способом указать что происходит смена состояний._ 
Заменил into => transition_to (commit: Rename events into => transition_to)

2021-12-10 06:44 UTC, greybutton approved these changes

2021-12-10 09:39 UTC, merged